#pass files between jobs in github actions

name: pass files btw jobs
on: [ push, workflow_dispatch ]
jobs:
   job1: 
      runs-on: ubunutu-latest
      steps:
        - name: creating a files
          run: echo "123445" > file1.txt

        - name: upload files
          uses: actions/upload-artifact@v4
          with:
            name: file1
            path: file1.txt

   job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - name: download files
          uses: actions/download-artifact@v4
          with:
            name: file1

        - name: dislay file content
          run: cat file1.txt             