name: pass folders btx jobs github actions
on: [ push, workflow_dispatch ]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: creating files
              run: |
                  mkdir sample-folder
                  echo "This is a sample file content" > sample-folder/sample.txt

            - name: upload files
              uses: actions/upload-artifact@v4
              with:
                  name: sample-folder
                  path: sample-folder/sample.txt


    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: download files
              uses: actions/download-artifact@v4
              with:
                  name: sample-folder

            - name: display file content
              run: cat sample-folder/sample.txt  