name: pass files btx jobs github actions
on: [ push, workflow_dispatch ]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: creating files
              run: echo "This is a sample file content" > sample.txt

            - name: upload files
              uses: actions/upload-artifact@v4
              with:
                  name: sample-file
                  path: sample.txt


    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: download files
              uses: actions/download-artifact@v4
              with:
                  name: sample-file

            - name: display file content
              run: cat sample.txt              