name: selective job run
on:
    workflow_dispatch:
        inputs:
            select-job:
                description: 'Select the job to run (job1, job2, job3, all)'
                required: true
                default: 'job1'
                type: choice
                options:
                    - job1
                    - job2
                    - job3
                    - all


jobs:
    job1:
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs['select-job'] == 'job1' || github.event.inputs['select-job'] == 'all' }}
        steps:
            - name: Run Job 1
              run: echo "This is Job 1"

    job2:
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs['select-job'] == 'job2' || github.event.inputs['select-job'] == 'all' }}
        steps:
            - name: Run Job 2
              run: echo "This is Job 2"

    job3:
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs['select-job'] == 'job3' || github.event.inputs['select-job'] == 'all' }}
        steps:
            - name: Run Job 3
              run: echo "This is Job 3"