name: sequential-1 jobs demo
on:
    push:
      branches:
        - main

    workflow_dispatch:
jobs:
   first-job: 
      runs-on: ubuntu-latest
      steps:
        - name: step-1
          run: exit 1

   second-job:
      runs-on: ubuntu-latest  
      needs: first-job
      if: ${{ always() }}
      steps:  
        - name: step-2
          run: echo "This is the second job, running after the first job."

   third-job:
      runs-on: ubuntu-latest
      needs: second-job
      if: ${{ always() }}
      steps:
        - name: step-3
          run: echo "This is the third job, running after the second job."