name: sequential jobs demo
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "This is the first job."

  second-job:
    runs-on: ubuntu-latest  
    
    steps:  
      - name: step-2
        run: echo "This is the second job, running after the first job."      

  third-job:
    runs-on: ubuntu-latest  
    
    steps:  
      - name: step-3
        run: echo "This is the third job, running after the second job."    

  fourth-job:
    runs-on: ubuntu-latest  
    
    steps:  
      - name: step-4
        run: echo "This is the fourth job, running after the first, second, and third jobs."                